### ISSUE TITLE
NodeJS12 actions are deprecated

### ISSUE THREAD

**Issue by BijoyFrancis** [infracost/actions#122]
I can see the below error while running the action. Hope this would be taken care.

infra-costProcess completed with exit code 1.
infra-costNode.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: infracost/actions

**Comment by aliscott** [comment]
Thanks for reporting @BijoyFrancis. We will look at updating to node 16.

**Comment by gogorichie** [comment]
Excited to see this issue get resolved in the future!

**Comment by sunnyoswalcro** [comment]
@aliscott any update ?

**Comment by alikhajeh1** [comment]
Hi everyone, we're going to work on this next week! We thought we had until Summer 2023 to do this as the GH announcement blog mentioned "We plan to migrate all actions to run on Node16 by Summer 2023", however, [another community member](https://github.com/infracost/actions/issues/151) mentioned that their github action is failing (not just a warning) so we're going to jump on this.

**Comment by tim775** [comment]
@BijoyFrancis @sunnyoswalcro @gogorichie  We've released [v2.1.0](https://github.com/infracost/actions/releases/tag/v2.1.0) which uses node 16.  If you are using the @v2 tag you will get that version automatically.  Sorry for the delay on this and thank your for your patience!
