### ISSUE TITLE
github action infracost/actions/setup@v2 failing because node12 is blocked by github

### ISSUE THREAD

**Issue by momelod** [infracost/actions#151]
# error i see in the github action logs:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: infracost/actions/setup@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
#  should use node16
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
https://github.com/infracost/actions/blob/e9246a542d5a304713b42ff612bf3a2b335e0637/setup/action.yml#L26

**Comment by alikhajeh1** [comment]
@momelod there's already an open issue https://github.com/infracost/actions/issues/122, can you just clarify that your github action is not failing? it's showing a `deprecated` warning?

**Comment by alikhajeh1** [comment]
Closing this as we're tracking it in #122

**Comment by momelod** [comment]
for me it was failing.

**Comment by alikhajeh1** [comment]
@momelod thanks for confirming! The GH announcement mentioned that "We plan to migrate all actions to run on Node16 by Summer 2023." so I'm surprised that it's failing for you. Anyway, we'll look at this on next week and I'll report back on #122 so please stay tuned!
