### ISSUE TITLE
Increment to Node 20

### ISSUE THREAD

**Issue by jdagostino9188** [infracost/actions#180]
GitHub is deprecating Node 16 this spring.  Infracost is currently using Node 16 so all actions-invoked Infracost runs will fail.  Please increment to Node 20.

Warning Message:
```Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: webfactory/ssh-agent@v0.8.0, infracost/actions/setup@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.```

**Comment by aliscott** [comment]
Thanks @jdagostino9188 🙏 I've added a task for us to do this sometime this month.
