### ISSUE TITLE
 actions/checkout@v3 use node version that is going to be deprecated

### ISSUE THREAD

**Issue by galbaneim-orca** [infracost/actions#199]
# Checkout the branch you want Infracost to compare costs against, most commonly the target branch.
    - name: Checkout base branch
      uses: actions/checkout@v3
      with:
        ref: '${{ github.event.pull_request.base.ref }}'

The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3

can you update the it to actions/checkout@v4

**Comment by vdmgolub** [comment]
Fixed in #200. Thank you for creating the issue! 👍
