### ISSUE TITLE
post_condition seems to have disapeared from new GH Action 

### ISSUE THREAD

**Issue by glebourgeois** [infracost/actions#80]
In the [previous github action](https://github.com/infracost/infracost-gh-action), there were several options to post infracost comments in PR only under conditions, with the `post_condition` JSON string

- has_diff
- percentage_threshold

This was really useful to post comments only when necessary, and avoid adding noise in the pull requests.

As these options seem to have disappeared, is there an alternative?

**Comment by hugorut** [comment]
Hey @glebourgeois, 

Thanks for raising this issue. So the `has_diff` functionality has been replaced by the `Infracost comment` `--behavior=update` flag. This only updates a PR comment if there is a change in costs.

Regarding the `percentage_threshold`, we have removed this option in favour of a more flexible approach, allowing users to define the specifics of how they want their comments posted. Infracost integrates with cost policy engines like sentinel and OPA. You can check out our sentinel [example here](https://github.com/infracost/actions/tree/master/examples/sentinel) and read more about our native integration with [OPA here](https://www.infracost.io/docs/features/cost_policies/#option-1-open-policy-agent-opa).

If you're looking for a native bash/actions way to post a comment conditionally, you can always pick values out of our output. I'd recommend looking at this issue: https://github.com/infracost/infracost/issues/1472 for more information.

I will close this issue but feel free to ping me if you have further questions.
